version: '3.8'

services:

  authorization_web:
    build: ./services/authorization
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./services/authorization:/usr/src/app
    depends_on:
      - redis
      - postgres_db_container

  authorization_worker:
    build: ./services/authorization
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./services/authorization:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - authorization_web
      - redis
    user: celeryuser

  redis:
    image: redis:7
  postgres_db_container:
    container_name: postgres_db_container
    hostname: postgres_db_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres_db_container
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: authorization